---
title: "Atividade de Análise de Clusters"
output: html_notebook
---

#Base de Dados

```{r}
# Designar work directory.
setwd("C:/Users/rodto/OneDrive/04 Profissional/03 Letivas/04 FGV/02 MBA BA BigData/04 Disciplinas/08 Matrizes e Clusters/04 An Clusters/")
getwd()
```

```{r}
# Ler os dados do arquivo Excel no work directory.
#install.packages("readxl")
library(readxl)
ATIBAIA <- read_xlsx("ATIBAIA.xlsx", sheet = "ATIBAIA", col_names = TRUE)
```

#Estudo e Avaliação dos Dados

```{r}
# Mapear os tipos dos dados das colunas da tabela importada.
sapply(ATIBAIA, class)
# Sumarizar as características univariadas dos dados da tabela importada.
summary(ATIBAIA)
# Repare que as variáveis biling, estac e ti estão sendo erroneamente sendo tratadas como numéricas, quando na verdade são fatores.
```

```{r}
# Mudar o tipo das variáveis biling, estac e ti para factor.
ATIBAIA$biling=as.factor(ATIBAIA$biling)
ATIBAIA$estac=as.factor(ATIBAIA$estac)
ATIBAIA$ti=as.factor(ATIBAIA$ti)
# Refazer a sumarização das características univariadas dos dados da tabela importada, agora com os tipos das colunas corrigidos.
summary(ATIBAIA)
```

```{r}
# Selecionar somente as variáveis drivers de clustering (filial não é porque é apenas o nome da filial, aval_global não é porque é uma composição das outras variáveis, e idade também não é porque não é um fator caracterizador relevante).
ATIBAIA_drivers = ATIBAIA[ , -c(1,2,9)]
```

#Algoritmos Nativos do R (patote 'stats')

##An. de Clusters POR PARTIÇÃO: K-Means

```{r}
# Preparando dados, transformando tudo para tipo numérico e colocando as colunas em escala.
ATIBAIA_drivers_num <- ATIBAIA_drivers
ATIBAIA_drivers_num$biling = as.numeric(ATIBAIA_drivers_num$biling)
ATIBAIA_drivers_num$estac = as.numeric(ATIBAIA_drivers_num$estac)
ATIBAIA_drivers_num$ti = as.numeric(ATIBAIA_drivers_num$ti)

ATIBAIA_drivers_num_z <- as.data.frame(lapply(ATIBAIA_drivers_num, scale))
```

```{r}
# Calculando a correlação entre as variáveis. Deve-se tomar o cuidado de que não hajam grandes correlações entre as variáveis, pois estaríamos considerando a mesma informação repetidas vezes, aumentando o "peso" daquela informação na formação dos clusters.
cor(ATIBAIA_drivers_num_z)
# Ok, não existem grandes correlações.
```


#-------------------------------------------------------------------------
# Para centers = 1


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 1, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- KMeans_clustering_k3$withinss
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- KMeans_clustering_k3$betweenss
```


#-------------------------------------------------------------------------
# Para centers = 2


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 2, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 3


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 3, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 4


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 4, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 5


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 5, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 6


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 6, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 7


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 7, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 8


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 8, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 9


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 9, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 10


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 10, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 11


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 11, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```


#-------------------------------------------------------------------------
# Para centers = 12


```{r}
# A função mais utilizada para operacionalizar o K-Means é a kmeans, nativa do R vinculada à biblioteca stats, também nativa do R. Por ser uma biblioteca nativa, não há necessidade de carregar a biblioteca pois a mesma já é naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 12, nstart = 20)
KMeans_clustering_k3
```

```{r}
# Soma de distâncias quadráticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
withinss <- c(withinss, sum(KMeans_clustering_k3$withinss))
```

```{r}
# Soma total de distâncias quadráticas entre observações de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
betweenss <- c(betweenss, KMeans_clustering_k3$betweenss)
```

#-------------------------------------------------------------------------
# Resultado

```{r}
# Gráfico de Withinss e Betweenss

plot(withinss, type = "b", frame = TRUE, pch = 19,
     col = "red", xlab = "Clusters", ylab = "y", 
     lty = 1, lwd = 1)

lines(betweenss, pch = 19, col = "blue", type = "b", 
      lty = 1, lwd = 1)

legend("top", legend = c("Withinss", "Betweenss"),
       col = c("red", "blue"), lty = 1:1, cex = 0.8)

```


```{r}
# Outra opção de gráfico

library(factoextra)
fviz_nbclust(x = ATIBAIA_drivers_num_z,FUNcluster = kmeans, method = 'wss' )
```


#-------------------------------------------------------------------------
# Plot dos Clusters


```{r}
# Carregar pacote fpc (Flexible Procedures for Clustering), que possui uma série de funções para análise de clusters.
library(fpc)
# Utilizar a função plotcluster do pacote fpc, que imprime o gráfico espacial nas duas componentes principais mais relevantes.
plotcluster(ATIBAIA_drivers_num_z, KMeans_clustering_k3$cluster)
# Nota-se que os grupos estão bem separados, o que é um bom sinal.
```

```{r}
#install.packages("factoextra")
library(factoextra)
fviz_cluster(list(data = ATIBAIA_drivers_num_z, cluster = KMeans_clustering_k3$cluster),  show.clust.cent = T)

```
